FROM node:22.16.0

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir numpy --break-system-packages

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm install python-shell

CMD ["npm", "start"]